name: Publish stable release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release

    strategy:
      matrix:
        kind: ['linuxselfcontained', 'linux', 'windows']
        include:
          - kind: linuxselfcontained
            os: ubuntu-latest
            target: linux-x64
            frameworktype: --self-contained
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
            frameworktype: --no-self-contained
          - kind: windows
            os: windows-latest
            target: win-x64
            frameworktype: --no-self-contained

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dotnet 
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Build EthernaVideoImporter project
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="etherna-video-importer-$tag-${{ matrix.kind }}"
          # Build everything
          dotnet publish src/EthernaVideoImporter/EthernaVideoImporter.csproj --runtime "${{ matrix.target }}" "${{ matrix.frameworktype }}" -c Release -o "$release_name"
          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            7z a -tzip "${release_name}.zip" "./${release_name}/*"
          else
            tar czvf "${release_name}.tar.gz" "$release_name"
          fi

      - name: Build EthernaVideoImporter.Devcon project
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="devcon-archive-video-importer-$tag-${{ matrix.kind }}"
          # Build everything
          dotnet publish src/EthernaVideoImporter.Devcon/EthernaVideoImporter.Devcon.csproj --runtime "${{ matrix.target }}" "${{ matrix.frameworktype }}" -c Release -o "$release_name"
          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            7z a -tzip "${release_name}.zip" "./${release_name}/*"
          else
            tar czvf "${release_name}.tar.gz" "$release_name"
          fi

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: |
            "etherna-video-importer-*"
            "devcon-archive-video-importer-*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
